version: "3.8"

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: unleash
      POSTGRES_USER: unleash
      POSTGRES_PASSWORD: unleash
    ports:
      - "5432:5432"
    volumes:
      - unleash_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U unleash -d unleash"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - ffnet

  unleash-server:
    image: unleashorg/unleash-server
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://unleash:unleash@postgres:5432/unleash
      DATABASE_SSL: "false"
      UNLEASH_PORT: "4242"
      UNLEASH_DEFAULT_ADMIN_USERNAME: admin
      UNLEASH_DEFAULT_ADMIN_PASSWORD: admin
    ports:
      - "4242:4242"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:4242/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - ffnet

  product-service:
    build: ./product-service
    depends_on:
      unleash-server:
        condition: service_healthy
    environment:
      UNLEASH_API_URL: http://unleash-server:4242/api
      UNLEASH_API_TOKEN: default:development.a38b892351f4413040305e771742236d549f11549ce57c898f98ee1b
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - ffnet

  order-service:
    build: ./order-service
    depends_on:
      product-service:
        condition: service_healthy
    environment:
      UNLEASH_API_URL: http://unleash-server:4242/api
      UNLEASH_API_TOKEN: default:development.a236f959abf1d07d5a5f30be1dac68fa3288bec6ae223af70b36ed3e
      PRODUCT_SERVICE_URL: http://product-service:8080
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - ffnet

volumes:
  unleash_pgdata:

networks:
  ffnet:
